parent/pom.xml

In order to override it in devstudio

JBDS-3408: Make p2StatsUrl a property

---

parent/pom.xml

prepare for Final

---

parent/pom.xml

[JBIDE-23262] - Parent POM wrongly configured for AM1

---

parent/pom.xml

so that Itests would build against the proper tpc

Set tpc version for the whole ITests profile

---

parent/pom.xml

Update devstudioRepository propery in pom.xml to use Oxygen update site.

Update devstudioRepository prop. to use Oxygen update site

---

parent/pom.xml

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

JBIDE-25223 - unify sonar maven plugin version

---

parent/pom.xml

[JBIDE-25744] - JDK9 profile should be auto detected and allow next version of Java (10,...)

---

parent/pom.xml

Update JaCoCo versions for JDK 10 and 11

---

parent/pom.xml

Update baseline following major release

---

parent/pom.xml

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

JBIDE-26457 Update tycho to 1.3.0-SNAPSHOT in parent pom

---

parent/pom.xml

JBIDE-26469 - Add jdk12 profile

---

parent/pom.xml

JBIDE-26469 - Update jdeps profile

---

parent/pom.xml

Switch to Tycho 1.3.0

---

parent/pom.xml

1.3.0-SNAPSHOT)
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

JBIDE-26516 Update parameter jbossTychoPluginsVersion to 1.3.0(from

---

parent/pom.xml

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

Adding missing jre 11 into global properties

---

parent/pom.xml

Switch to Tycho 1.4.0

---

parent/pom.xml

JBIDE-26671: Switch URLs to https

---

parent/pom.xml

JBIDE-26863: added quarkus site properties

---

parent/pom.xml

3.6.0.1398
Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

JBIDE-26644 Update jacoco plugin to 0.8.4 and sonar maven plugin to

---

parent/pom.xml

JBIDE-26908: Switch to tycho 1.5.1

---

parent/pom.xml

JBIDE-27014: switch to tycho 1.6.0

---

parent/pom.xml

Add Java14

---

parent/pom.xml

JBIDE-27208: switch to tycho 1.7.0

---

parent/pom.xml

Signed-off-by: Josef Kopriva <jkopriva@redhat.com>

JBIDE-27320 Remove old JRE variables from parent pom

---

parent/pom.xml

Add JBoss Third Party releases repo (required for released quarkus-ls)

---

parent/pom.xml

Fix repo id

---

parent/pom.xml

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

Add jdk15 profile for toolchains

---

parent/pom.xml

JBIDE-27614: Update to tycho 2.2.0

---

parent/pom.xml

JBIDE-27844: PR checks failing on Gitub because of an http repository

---

parent/pom.xml

JBIDE-27974: update to jacoco  0.8.7

---

parent/pom.xml

Signed-off-by: Oleksii Korniienko <olkornii@redhat.com>

added jre-17 to parent/pom.xml

---

parent/pom.xml

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

JBIDE-28371 Switch to JBT p2 update site and eclipse app for test base

---

parent/pom.xml

Signed-off-by: Lukas Grossmann <lgrossma@redhat.com>

Changing install OSX path to eclipse

---

parent/pom.xml

JBIDE-28477: update parent pom to tycho and jboss maven 2.7.5

---

parent/pom.xml

JBIDE-28816 : Fix Unexpected excessively log output during tests
